" vimrc by ashik992
set nocompatible               " be iMproved
 filetype off                   " required!

 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()

 " let Vundle manage Vundle
 " required!
 Bundle 'gmarik/vundle'

 " My Bundles here:
 Bundle 'https://github.com/Yggdroot/indentLine.git'
 Bundle 'https://github.com/jiangmiao/auto-pairs.git'
 Bundle 'https://github.com/vim-scripts/CursorLineCurrentWindow.git'

 let g:indentLine_char = '┆'
 :set cursorline
